name: Chatr Firebase Hosting

on:
  push:
    branches:
      - master
      - stable-release
      - feat/*

jobs:
  deploy:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Download Dependencies
        run: npm i

      - name: Build
        run: npm run build
        env:
          REACT_APP_GIT_SHA: ${{ github.SHA }}

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
